#!/usr/bin/env bash
#
# hash-release.sh - Generate SHA256 checksums for release artifacts
#
# Usage:
#   ./hash-release.sh <directory> [--sign-with-gpg KEYID]
#
# Generates:
#   CHECKSUMS.txt        - All SHA256 checksums
#   CHECKSUMS.txt.sha256 - SHA256 of CHECKSUMS.txt itself
#   CHECKSUMS.txt.asc    - PGP signature of CHECKSUMS.txt (if --sign-with-gpg)
#   RELEASE_NOTES.txt   - Template for release notes
#   RELEASE_NOTES.txt.asc - PGP signature (if --sign-with-gpg)
#
# The CHECKSUMS.txt file can be verified with:
#   sha256sum -c CHECKSUMS.txt
#

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

usage() {
    echo "Usage: $0 <directory> [--sign-with-gpg KEYID]"
    echo ""
    echo "Arguments:"
    echo "  directory           Directory containing release files"
    echo "  --sign-with-gpg     GPG key ID to sign checksums (optional)"
    echo ""
    echo "Examples:"
    echo "  $0 ./releases/"
    echo "  $0 ./releases/ --sign-with-gpg ABCD1234EFGH5678"
    exit 1
}

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
RELEASE_DIR=""
GPG_KEYID=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sign-with-gpg)
            GPG_KEYID="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            if [[ -z "$RELEASE_DIR" ]]; then
                RELEASE_DIR="$1"
            else
                log_error "Unknown argument: $1"
                usage
            fi
            shift
            ;;
    esac
done

# Validate
if [[ -z "$RELEASE_DIR" ]]; then
    log_error "Missing release directory"
    usage
fi

# Resolve path
RELEASE_DIR="$(realpath "$RELEASE_DIR")"

if [[ ! -d "$RELEASE_DIR" ]]; then
    log_error "Directory not found: $RELEASE_DIR"
    exit 1
fi

# Find files (exclude generated files themselves)
EXCLUDE_PATTERN="CHECKSUMS.txt|CHECKSUMS.txt.sha256|CHECKSUMS.txt.asc|RELEASE_NOTES.txt|RELEASE_NOTES.txt.asc"
FILES=$(find "$RELEASE_DIR" -maxdepth 1 -type f ! -name "$EXCLUDE_PATTERN" | sort)

if [[ -z "$FILES" ]]; then
    log_error "No files found in $RELEASE_DIR (excluding checksums)"
    exit 1
fi

# Count files
FILE_COUNT=$(echo "$FILES" | wc -l)

log_info "Generating checksums for $FILE_COUNT file(s) in:"
log_info "  $RELEASE_DIR"

# Generate CHECKSUMS.txt
CHECKSUMS_FILE="$RELEASE_DIR/CHECKSUMS.txt"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "# CHECKSUMS.txt - Generated by regen-app-stack" > "$CHECKSUMS_FILE"
echo "# Generated: $TIMESTAMP" >> "$CHECKSUMS_FILE"
echo "# Algorithm: SHA256" >> "$CHECKSUMS_FILE"
echo "" >> "$CHECKSUMS_FILE"
echo "# SHA256 checksums" >> "$CHECKSUMS_FILE"
echo "# Verify with: sha256sum -c CHECKSUMS.txt" >> "$CHECKSUMS_FILE"
echo "" >> "$CHECKSUMS_FILE"

for file in $FILES; do
    basename_file=$(basename "$file")
    sha256=$(sha256sum "$file" | cut -d' ' -f1)
    printf "%s  %s\n" "$sha256" "$basename_file" >> "$CHECKSUMS_FILE"
done

echo "" >> "$CHECKSUMS_FILE"
echo "# Verification instructions:" >> "$CHECKSUMS_FILE"
echo "# 1. Download all files from the release directory" >> "$CHECKSUMS_FILE"
echo "# 2. Download CHECKSUMS.txt" >> "$CHECKSUMS_FILE"
echo "# 3. Run: sha256sum -c CHECKSUMS.txt" >> "$CHECKSUMS_FILE"
echo "# 4. All files should show 'OK'" >> "$CHECKSUMS_FILE"

log_info "Created CHECKSUMS.txt"

# Generate SHA256 of CHECKSUMS.txt itself
cd "$RELEASE_DIR"
sha256sum CHECKSUMS.txt > CHECKSUMS.txt.sha256
log_info "Created CHECKSUMS.txt.sha256 (checksum of CHECKSUMS.txt)"

# Optionally sign with GPG
if [[ -n "$GPG_KEYID" ]]; then
    if command -v gpg &> /dev/null; then
        log_info "Signing CHECKSUMS.txt with GPG key: $GPG_KEYID"
        gpg --armor --detach-sign --local-user "$GPG_KEYID" --output CHECKSUMS.txt.asc CHECKSUMS.txt
        log_info "Created CHECKSUMS.txt.asc"
    else
        log_warn "GPG not found, skipping signature"
    fi
fi

# Generate release notes template
NOTES_FILE="$RELEASE_DIR/RELEASE_NOTES.txt"
VERSION_HINT=$(ls "$RELEASE_DIR" | grep -E '\.(apk|tar|gz|zip)$' | head -1 | sed 's/\.[^.]*$//' | sed 's/-signed$//' || echo "VERSION")

cat > "$NOTES_FILE" << EOF
# Release Notes

## Version: $VERSION_HINT

## What's New
<!-- Describe changes in this release -->

## Security
<!-- Note any security fixes or considerations -->

## Downloads
$(for f in $FILES; do basename_f=$(basename "$f"); echo "- \`$basename_f\` (SHA256: see CHECKSUMS.txt)"; done)

## Verification

### SHA256 Checksum
\`\`\`bash
cd /path/to/download
sha256sum -c CHECKSUMS.txt
\`\`\`

### PGP Signature (if signed)
\`\`\`bash
gpg --verify CHECKSUMS.txt.asc CHECKSUMS.txt
\`\`\`

## Support
<!-- How to report issues, where to get help -->

## Source Code
<!-- Link to source repository and release tag -->

---
Released: $TIMESTAMP
EOF

log_info "Created RELEASE_NOTES.txt template"
log_info "Edit it to add release details before publishing"

# Summary
echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e "  ${BOLD}Release package ready${NC}"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Files generated:"
echo "  CHECKSUMS.txt         - SHA256 checksums for all files"
echo "  CHECKSUMS.txt.sha256  - Checksum of CHECKSUMS.txt"
if [[ -n "$GPG_KEYID" ]]; then
    echo "  CHECKSUMS.txt.asc     - PGP signature of CHECKSUMS.txt"
fi
echo "  RELEASE_NOTES.txt     - Template for release announcement"
echo ""
echo "Next steps:"
echo "  1. Edit RELEASE_NOTES.txt with actual release info"
echo "  2. If using GPG:"
echo "       gpg --armor --detach-sign --local-user $GPG_KEYID RELEASE_NOTES.txt"
echo "  3. Publish all files to your release page"
echo ""
echo "Users can verify with:"
echo "  sha256sum -c CHECKSUMS.txt"
if [[ -n "$GPG_KEYID" ]]; then
    echo "  gpg --verify CHECKSUMS.txt.asc CHECKSUMS.txt"
fi
echo ""
